---
- include_vars: "{{ ansible_os_family }}.yml"
- include: "install-{{ ansible_os_family }}.yml"

- name: Create snmpd.conf
  template:
    src: snmpd.conf.j2
    dest: "{{ snmpd_conf_file }}"
    validate: "{{ snmpd_bin }} -n -f %s"
  notify: Restart snmpd

- name: Ensure snmpd is started
  service:
    name: "{{ snmpd_service }}"
    state: started
